# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html

### Uebersicht
GET {{baseUrl}}/actuator
Authorization: {{basic-auth}}

### Mapping von HTTP-Requests, z.B.   GET && /
GET {{baseUrl}}/actuator/mappings
Authorization: {{basic-auth}}

### Info
GET {{baseUrl}}/actuator/info
Authorization: {{basic-auth}}

### Laeuft der Server in gutem Zustand ?
GET {{baseUrl}}/actuator/health

### Shutdown
POST {{baseUrl}}/actuator/shutdown
Authorization: {{basic-auth}}
Content-Type: application/json

### Performance-Daten beim Serverstart, z.B. ueber gestartete Beans (erfordert BufferingApplicationStartup)
#POST {{baseUrl}}/actuator/startup
#Authorization: {{basic-auth}}

### Spring Beans
#GET {{baseUrl}}/actuator/beans
#Authorization: {{basic-auth}}

### Umgebung und Properties
#GET {{baseUrl}}/actuator/env
#Authorization: {{basic-auth}}

###
