# https://www.jetbrains.com/help/idea/rest-client-in-intellij-idea-code-editor.html
# https://blog.jetbrains.com/idea/2017/09/whats-new-in-intellij-idea-2017-3-eap
# https://blog.jetbrains.com/phpstorm/2017/09/editor-based-rest-client
# https://youtrack.jetbrains.com/issue/WEB-28559
# https://youtrack.jetbrains.com/issue/WEB-28638

### Suche alle Labore (<Strg><Click> fuer Web Browser)
GET {{baseUrl}}/api
Accept: application/hal+json
Authorization: {{basic-auth}}
ALPN: h2

### Suche mit vorhandener Labor-ID
GET {{baseUrl}}/api/api/00000000-0000-0000-0000-000000000001
Accept: application/hal+json
Authorization: {{basic-auth}}
ALPN: h2

### Suche mit vorhandener Labor-ID und application/json (404)
GET {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Accept: application/json
Authorization: {{basic-auth}}
ALPN: h2

### Suche mit nicht-vorhandener Labor-ID
GET {{baseUrl}}/api/f9999999-9999-9999-9999-999999999999
Authorization: {{basic-auth}}
ALPN: h2

### Suche mit vorhandenem Namen
GET {{baseUrl}}/api?name=Hahn
Accept: application/hal+json
Authorization: {{basic-auth}}
ALPN: h2

### Suche mit nicht-vorhandenem Namen
GET {{baseUrl}}/api?name=Zeta
Accept: application/hal+json
Authorization: {{basic-auth}}
ALPN: h2


### Streaming mit allen Labore
GET {{baseUrl}}/api
Accept: text/event-stream
Authorization: {{basic-auth}}
ALPN: h2

###
