### Ein Labor mittels PUT aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Content-Type: application/json
Authorization: {{basic-auth}}
ALPN: h2

< data/labor-put.json

### Ein Labor mit fehlerhaften Werten mittels PUT aktualisieren
PUT {{baseUrl}}/api/00000000-0000-0000-0000-000000000001
Content-Type: application/json
Authorization: {{basic-auth}}
ALPN: h2

< data/labor-put-invalid.json

###
