// Startseite
GET {{baseUrl}}/home
Accept: text/html
Authorization: {{basic-auth}}
Host: {{host}}
ALPN: h2

###

// Suche alle
GET {{baseUrl}}/suche
Accept: text/html
Authorization: {{basic-auth}}
Host: {{host}}
ALPN: h2

###

// Detailanzeige
GET {{baseUrl}}/details?id=00000000-0000-0000-0000-000000000001
Accept: text/html
Authorization: {{basic-auth}}
Host: {{host}}
ALPN: h2
